import pandas as pd

# Load dataset
df = pd.read_csv("update_epidemic_data_swapped.csv")

# Define custom country names mapping for 100 countries
custom_country_names = {
    'USA': 'United States',
    'CAN': 'Canada',
    'MEX': 'Mexico',
    'BRA': 'Brazil',
    'ARG': 'Argentina',
    'GBR': 'United Kingdom',
    'FRA': 'France',
    'DEU': 'Germany',
    'ITA': 'Italy',
    'ESP': 'Spain',
    'RUS': 'Russia',
    'CHN': 'China',
    'IND': 'India',
    'JPN': 'Japan',
    'AUS': 'Australia',
    'ZAF': 'South Africa',
    'EGY': 'Egypt',
    'NGA': 'Nigeria',
    'KEN': 'Kenya',
    'ETH': 'Ethiopia',
    'SAU': 'Saudi Arabia',
    'IRN': 'Iran',
    'TUR': 'Turkey',
    'ISR': 'Israel',
    'KOR': 'South Korea',
    'IDN': 'Indonesia',
    'PAK': 'Pakistan',
    'BGD': 'Bangladesh',
    'PHL': 'Philippines',
    'VNM': 'Vietnam',
    'THA': 'Thailand',
    'MYS': 'Malaysia',
    'SGP': 'Singapore',
    'NZL': 'New Zealand',
    'CHL': 'Chile',
    'COL': 'Colombia',
    'PER': 'Peru',
    'VEN': 'Venezuela',
    'URY': 'Uruguay',
    'PRY': 'Paraguay',
    'BOL': 'Bolivia',
    'ECU': 'Ecuador',
    'GTM': 'Guatemala',
    'HND': 'Honduras',
    'SLV': 'El Salvador',
    'NIC': 'Nicaragua',
    'CRI': 'Costa Rica',
    'PAN': 'Panama',
    'CUB': 'Cuba',
    'HTI': 'Haiti',
    'DOM': 'Dominican Republic',
    'JAM': 'Jamaica',
    'TTO': 'Trinidad and Tobago',
    'GUY': 'Guyana',
    'SUR': 'Suriname',
    'BRA': 'Brazil',
    'ARG': 'Argentina',
    'URY': 'Uruguay',
    'PRY': 'Paraguay',
    'BOL': 'Bolivia',
    'CHL': 'Chile',
    'PER': 'Peru',
    'ECU': 'Ecuador',
    'COL': 'Colombia',
    'VEN': 'Venezuela',
    'GUY': 'Guyana',
    'SUR': 'Suriname',
    'GTM': 'Guatemala',
    'HND': 'Honduras',
    'SLV': 'El Salvador',
    'NIC': 'Nicaragua',
    'CRI': 'Costa Rica',
    'PAN': 'Panama',
    'CUB': 'Cuba',
    'HTI': 'Haiti',
    'DOM': 'Dominican Republic',
    'JAM': 'Jamaica',
    'TTO': 'Trinidad and Tobago',
    'GUY': 'Guyana',
    'SUR': 'Suriname',
    'BRA': 'Brazil',
    'ARG': 'Argentina',
    'URY': 'Uruguay',
    'PRY': 'Paraguay',
    'BOL': 'Bolivia',
    'CHL': 'Chile',
    'PER': 'Peru',
    'ECU': 'Ecuador',
    'COL': 'Colombia',
    'VEN': 'Venezuela',
    'GUY': 'Guyana',
    'SUR': 'Suriname',
    'GTM': 'Guatemala',
    'HND': 'Honduras',
    'SLV': 'El Salvador',
    'NIC': 'Nicaragua',
    'CRI': 'Costa Rica',
    'PAN': 'Panama',
    'CUB': 'Cuba',
    'HTI': 'Haiti',
    'DOM': 'Dominican Republic',
    'JAM': 'Jamaica',
    'TTO': 'Trinidad and Tobago',
    'GUY': 'Guyana',
    'SUR': 'Suriname',
    # Add more mappings as needed
}

# Fill missing values in the "Country" column using the custom country names mapping
df['Country'] = df.apply(lambda row: custom_country_names.get(row['ISO Code'], row['Country']) if pd.isnull(row['Country']) else row['Country'], axis=1)

# Check missing values after filling
missing_values = df.isnull().sum()
print("Missing Values after filling:\n", missing_values)

# Save the updated DataFrame to a new CSV file
df.to_csv("update_epidemic_data_filled_custom.csv", index=False)
print("Updated data saved as update_epidemic_data_filled_custom.csv.")